### ISSUE TITLE
Image Date

### ISSUE THREAD

**Issue by uffsalot** [mspark/MultiModuleCatBot#2]
It would be nice if the EXIF date is attached as a comment to the image. 
So the user can better classify the images in time. Helpful for kitten progress ;)

**Comment by mspark** [comment]
Approved.

**Comment by mspark** [comment]
https://github.com/mspark/MultiModuleCatBot/tree/ft_exifData

Was merged. 

![Screenshot_20210122_171349](https://user-images.githubusercontent.com/14931470/105515623-32807180-5cd5-11eb-86c2-1ad6a11a02f9.png)

If you request any other additional information, pls answer here.
